### Installation command : pip install numpy

In [1]:
import numpy as np

## Creating Numpy arrays from existing Python lists

In [2]:
my_list = [1, 2, 3, 4, 5]

In [3]:
my_np_array = np.array(my_list)

In [4]:
my_np_array

array([1, 2, 3, 4, 5])

In [5]:
my_3d_np_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [6]:
my_3d_np_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
my_3d_np_array.shape

(3, 3)

In [9]:
my_2d_array = np.array([[1, 2, 3], [4, 5, 6]])

In [11]:
my_2d_array.shape

(2, 3)

In [12]:
my_2d_array

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
type(my_2d_array)

numpy.ndarray

## Functions for creating arrays

In [15]:
zero_array = np.zeros((3,4))

In [16]:
zero_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
ones_array = np.ones((3, 4))

In [18]:
ones_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
identity_matrix = np.eye(4)

In [20]:
identity_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
random_array = np.random.random((3, 4))

In [22]:
random_array

array([[0.75527268, 0.94892758, 0.35215553, 0.39181468],
       [0.08054318, 0.9459249 , 0.15876266, 0.08821387],
       [0.27869227, 0.36388162, 0.77709753, 0.07651624]])

In [23]:
increment_array = np.arange(6)

In [24]:
increment_array

array([0, 1, 2, 3, 4, 5])

In [27]:
increment_array_2 = np.arange(6, 12)

In [28]:
increment_array_2

array([ 6,  7,  8,  9, 10, 11])

In [30]:
increment_array_3 = np.arange(6, 12, 0.5)

In [31]:
increment_array_3

array([ 6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. ,
       11.5])

In [32]:
# Reference : https://docs.scipy.org/doc/numpy/user/basics.creation.html