# At the start of this video  
1. We were able to create numpy arrays.
2. We were able to do slicing and masking on numpy arrays.

In [1]:
import numpy as np

In [2]:
arr1 = np.array([1, 2, 3, 4, 5, 6])

In [3]:
arr1 * 2

array([ 2,  4,  6,  8, 10, 12])

In [4]:
arr1 ** 3

array([  1,   8,  27,  64, 125, 216])

In [5]:
arr1/ 5.0

array([0.2, 0.4, 0.6, 0.8, 1. , 1.2])

In [6]:
arr2 = np.array([10, 20, 30, 40, 50, 60])

In [7]:
arr1 + arr2

array([11, 22, 33, 44, 55, 66])

In [8]:
np.multiply(arr1, arr2)

array([ 10,  40,  90, 160, 250, 360])

In [9]:
arr2d = np.array([arr1, arr2])

In [10]:
arr2d

array([[ 1,  2,  3,  4,  5,  6],
       [10, 20, 30, 40, 50, 60]])

In [11]:
arr2d

array([[ 1,  2,  3,  4,  5,  6],
       [10, 20, 30, 40, 50, 60]])

In [12]:
arr2d * 3

array([[  3,   6,   9,  12,  15,  18],
       [ 30,  60,  90, 120, 150, 180]])

In [13]:
arr2d * 4

array([[  4,   8,  12,  16,  20,  24],
       [ 40,  80, 120, 160, 200, 240]])

# Example of broadcasting

In [14]:
arr4times = arr2d * 4

In [15]:
arr4times

array([[  4,   8,  12,  16,  20,  24],
       [ 40,  80, 120, 160, 200, 240]])

In [16]:
arr_sub = np.arange(6)
arr_sub

array([0, 1, 2, 3, 4, 5])

In [17]:
#[[  4,   8,  12,  16,  20,  24],  + [[0, 1, 2, 3, 4, 5]
# [ 40,  80, 120, 160, 200, 240]]    [0, 1, 2, 3, 4, 5]]


arr4times + arr_sub

array([[  4,   9,  14,  19,  24,  29],
       [ 40,  81, 122, 163, 204, 245]])

In [22]:
another_array = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

In [23]:
another_array

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [24]:
add_array = np.array([1, 2, 3])

In [25]:
# [[10, 20, 30],  +  [1, 2, 3]
#  [40, 50, 60],  +  [1, 2, 3]
#   [70, 80,90]]  +  [1, 2, 3]

another_array + add_array

array([[11, 22, 33],
       [41, 52, 63],
       [71, 82, 93]])

# By the end of this video  
1. We will be able to perform operations on numpy arrays.
2. We will understand how broadcasting works on numpy arrays.