In [1]:
import numpy as np

In [2]:
arr1 = np.array([1, 2, 3, 4, 5, 6])

In [3]:
arr1 * 2

array([ 2,  4,  6,  8, 10, 12])

In [5]:
arr1 ** 3

array([  1,   8,  27,  64, 125, 216])

In [7]:
arr2 = np.array([10, 20, 30, 40, 50, 60])

In [8]:
arr1 + arr2

array([11, 22, 33, 44, 55, 66])

In [9]:
np.multiply(arr1, arr2)

array([ 10,  40,  90, 160, 250, 360])

In [10]:
arr2d = np.array([arr1, arr2])

In [11]:
arr2d

array([[ 1,  2,  3,  4,  5,  6],
       [10, 20, 30, 40, 50, 60]])

In [13]:
arr2d * 3

array([[  3,   6,   9,  12,  15,  18],
       [ 30,  60,  90, 120, 150, 180]])

In [14]:
arr2d * 4

array([[  4,   8,  12,  16,  20,  24],
       [ 40,  80, 120, 160, 200, 240]])

# Example of broadcasting

In [15]:
arr4times = arr2d * 4

In [16]:
arr4times

array([[  4,   8,  12,  16,  20,  24],
       [ 40,  80, 120, 160, 200, 240]])

In [17]:
arr_sub = np.arange(6)
arr_sub

array([0, 1, 2, 3, 4, 5])

In [19]:
#[[  4,   8,  12,  16,  20,  24],  + [[0, 1, 2, 3, 4, 5]
# [ 40,  80, 120, 160, 200, 240]]    [0, 1, 2, 3, 4, 5]]


arr4times + arr_sub

array([[  4,   9,  14,  19,  24,  29],
       [ 40,  81, 122, 163, 204, 245]])

In [22]:
arr3d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [23]:
arr3d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
arr_add2 = np.array([10, 20, 30])

In [25]:
#[[1, 2, 3],   + [[10, 20, 30]
# [4, 5, 6],     [10, 20, 30]
# [7, 8, 9]]     [10, 20, 30]]
arr3d + arr_add2

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39]])