# At the beginning of this Video  
1. We understood the working to blocked algorithms in Dask.  
2. We knew about Dask Arrays and how they load large out-of-memory data.

In [1]:
import numpy as np
import dask.array as da

### Dask Arrays have similar interface to Numpy API

In [2]:
arr1 = np.random.random(10)
arr1

array([0.49173828, 0.15987751, 0.79051571, 0.46933163, 0.17073303,
       0.60611733, 0.42566986, 0.21060616, 0.04416578, 0.68829338])

In [3]:
dask_arr1 = da.random.random(10, chunks=3)

In [4]:
dask_arr1

dask.array<random_sample, shape=(10,), dtype=float64, chunksize=(3,)>

## Dask does lazy evaluation. We need to call compute() to execute statements

In [6]:
dask_arr1.compute()

array([0.36490282, 0.9504409 , 0.54994311, 0.06806324, 0.29098942,
       0.92964641, 0.55852606, 0.74064377, 0.92434251, 0.42027563])

In [8]:
dask_arr1.chunks

((3, 3, 3, 1),)

## Converting from Numpy array

In [10]:
dask_arr2 = da.from_array(arr1, chunks=4)
dask_arr2.compute()

array([0.49173828, 0.15987751, 0.79051571, 0.46933163, 0.17073303,
       0.60611733, 0.42566986, 0.21060616, 0.04416578, 0.68829338])

## Add two arrays

In [11]:
da_arr3 = da.random.random(1000000, chunks=1000)
da_arr4 = da.random.random(1000000, chunks=1000)

da_arr5 = da.add(da_arr3, da_arr4) #similar to numpy.add

In [12]:
da_arr5.compute()

array([0.73084104, 1.58611019, 0.26627761, ..., 1.27141123, 1.07443059,
       1.22270032])

# By the end of this video  
1. We will be able to use Dask Arrays  
2. We will be able to perform operations on Dask Arrays.  
3. We will also learn about how Dask arrays are stored in chunks.